name: Docker Check

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:
    merge_group:

concurrency:
    group: docker-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    docker_check_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build the docker-compose stack
              run: docker compose up -d

            - name: Sleep
              uses: jakejarvis/wait-action@master
              with:
                  time: '30s'

            - name: Verify containers
              run: |
                  CONTAINER_NAME=nango-server
                  SERVER=$(docker ps -q -f status=running -f name=^/${CONTAINER_NAME}$)
                  if [ ! "${SERVER}" ]; then
                    echo "Server container doesn't exist"
                    exit 1
                  fi

                  CONTAINER_NAME=nango-db
                  DB=$(docker ps -q -f status=running -f name=^/${CONTAINER_NAME}$)
                  if [ ! "${DB}" ]; then
                    echo "DB container doesn't exist"
                    exit 1
                  fi
              shell: bash
